src/Books/ViewModels/SearchViewModel.cs
using Books.Models;

namespace Books.ViewModels
{
    public class SearchDisplayViewModel
	{
        public IEnumerable<Book>? Book { get; set; }

		public string AuthorName { get; set; }

		public string SeriesName { get; set; }

		public IEnumerable<Author>? Author { get; set; }

        public IEnumerable<Series>? Series { get; set; }

	}

    public enum SearchFlag
    {
		Equal,
		More,
        Less
    }

	public class AuthorSearchViewModel
	{
		public Author Author { get; set; }

		public SearchFlag YearBirthFlag { get; set; }

		public SearchFlag YearDeathFlag { get; set; }
	}

	public class BookSearchViewModel
    {
        public Book Book { get; set; }

		public SearchFlag YearFlag { get; set; }

		public SearchFlag RatingFlag { get; set; }

		public string AuthorName { get; set; }

        public string SeriesName { get; set; }
    }

	public class SeriesSearchViewModel
	{
		public Series Series { get; set; }

		public SearchFlag YearFlag { get; set; }
		
		public SearchFlag RatingFlag { get; set; }
	}
}

src/Books/Controllers/SearchController.cs
using System.Diagnostics;
using Books.Models;
using Books.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Books.ViewModels;
using Books.Services;

namespace Books.Controllers
{
	public class SearchController : Controller
	{
		IAuthorService authorService;
		IBookService bookService;
		ISeriesService seriesService;

		public SearchController(IAuthorService authorService,
							  IBookService bookService,
							  ISeriesService seriesService)
		{
			this.authorService = authorService;
			this.bookService = bookService;
			this.seriesService = seriesService;
		}

		[HttpGet]
		public IActionResult SimpleSearch()
		{
			return View();
		}

		[HttpPost]
		public IActionResult SimpleSearch(string name)
		{
			IEnumerable<Author> authors = authorService.GetByName(name);
			IEnumerable<Book> books = bookService.GetByName(name);
			IEnumerable<Series> series = seriesService.GetByName(name);

			var searchDisplayViewModel = new SearchDisplayViewModel
			{
				Author = authors,
				Book = books,
				Series = series
			};

			return View("Display", searchDisplayViewModel);
		}

		[HttpGet]
		public IActionResult BookSearch()
		{
			return View();
		}

		[HttpPost]
		public IActionResult BookSearch(BookSearchViewModel model)
		{
			var booksByAthSer = new HashSet<Book>();
			IEnumerable<Book> booksByAuthor, booksBySeries;

			if (model.AuthorName != null && model.SeriesName != null)
			{
				booksByAuthor = bookService.GetByAuthor(model.AuthorName);
				booksBySeries = bookService.GetBySeries(model.SeriesName);
				booksByAthSer.UnionWith(booksByAuthor);
				booksByAthSer.IntersectWith(booksBySeries); ;
			}
			else if (model.AuthorName != null)
			{
				booksByAuthor = bookService.GetByAuthor(model.AuthorName);
				booksByAthSer.UnionWith(booksByAuthor);
			}
			else if (model.SeriesName != null)
			{
				booksBySeries = bookService.GetBySeries(model.SeriesName);
				booksByAthSer.UnionWith(booksBySeries);
			}

			IEnumerable<Book> books = booksByAthSer;

			books = bookService.GetByParameters(books, model.Book,
												model.YearFlag, model.RatingFlag);

			var searchDisplayViewModel = new SearchDisplayViewModel
			{
				Book = books,
				AuthorName = model.AuthorName,
				SeriesName = model.SeriesName
			};

			return View("Display", searchDisplayViewModel);
		}

		[HttpGet]
		public IActionResult AuthorSearch()
		{
			return View();
		}

		[HttpPost]
		public IActionResult AuthorSearch(AuthorSearchViewModel model)
		{
			IEnumerable<Author> authors = authorService.GetByParameters(model.Author,
																		model.YearBirthFlag,
																		model.YearDeathFlag);

			var searchDisplayViewModel = new SearchDisplayViewModel
			{
				Author = authors
			};

			return View("Display", searchDisplayViewModel);
		}

		[HttpGet]
		public IActionResult SeriesSearch()
		{
			return View();
		}

		[HttpPost]
		public IActionResult SeriesSearch(SeriesSearchViewModel model)
		{
			IEnumerable<Series> series = seriesService.GetByParameters(model.Series,
																		model.YearFlag,
																		model.RatingFlag);

			var searchDisplayViewModel = new SearchDisplayViewModel
			{
				Series = series
			};

			return View("Display", searchDisplayViewModel);
		}
	}
}

src/Books/Views/Search/AuthorSearch.cshtml
@using Books.ViewModels
@model AuthorSearchViewModel

<div class="advancedSearch-container">
	<div class="advancedSearch-inner-container">
		<h2>Расширенный поиск авторов</h2>

		@if (TempData["ErrorMessage"] != null)
		{
			<div class="alert alert-danger text-center">@TempData["ErrorMessage"]</div>
		}

		<form asp-action="AuthorSearch" asp-controller="Search">
			<div class="form-group">
				<input class="form"
					   asp-for="Author.Name"
					   placeholder="Имя"
					   type="text">
			</div>

			<div class="form-group">
				<input class="form"
					   asp-for="Author.Genre"
					   placeholder="Основной жанр"
					   type="text">
			</div>
		
			@if (User.Identity.IsAuthenticated)
			{
				<div class="form-group">
					<input class="form"
						   asp-for="Author.YearBirth"
						   placeholder="Год рождения"
						   type="text">
				</div>

				<div class="form-group">
					<label>Параметры года рождения:</label>

					<label class="toggle">
						<input type="radio" asp-for="YearBirthFlag" value="More" />
						<span class="checkmark"></span>
					</label>
					<label>Больше</label>

					<label class="toggle">
						<input type="radio" asp-for="YearBirthFlag" value="Less" />
						<span class="checkmark"></span>
					</label>
					<label>Меньше</label>

					<label class="toggle">
						<input type="radio" asp-for="YearBirthFlag" value="Equal" />
						<span class="checkmark"></span>
					</label>
					<label>Равно</label>
				</div>

				<div class="form-group">
					<input class="form"
						   asp-for="Author.YearDeath"
						   placeholder="Год смерти"
						   type="text">
				</div>

				<div class="form-group">
					<label>Параметры года смерти:</label>

					<label class="toggle">
						<input type="radio" asp-for="YearDeathFlag" value="More" />
						<span class="checkmark"></span>
					</label>
					<label>Больше</label>

					<label class="toggle">
						<input type="radio" asp-for="YearDeathFlag" value="Less" />
						<span class="checkmark"></span>
					</label>
					<label>Меньше</label>

					<label class="toggle">
						<input type="radio" asp-for="YearDeathFlag" value="Equal" />
						<span class="checkmark"></span>
					</label>
					<label>Равно</label>
				</div>
			}

			<div class="form-group">
				<input class="form"
					   asp-for="Author.Country"
					   placeholder="Страна проживания"
					   type="text">
			</div>

			<button type="submit" class="btn button">Найти</button>
		</form>
	</div>
</div>

src/Books/Views/Search/BookSearch.cshtml
@using Books.ViewModels
@model BookSearchViewModel

<div class="advancedSearch-container">
	<div class="advancedSearch-inner-container">
		<h2>Расширенный поиск книг</h2>

		@if (TempData["ErrorMessage"] != null)
		{
			<div class="alert alert-danger text-center">@TempData["ErrorMessage"]</div>
		}

		<form asp-action="BookSearch" asp-controller="Search">
			<div class="form-group">
				<input class="form"
					   asp-for="Book.Name"
					   placeholder="Название"
					   type="text">
			</div>
			<div class="form-group">
				<input class="form"
					   asp-for="Book.Genre"
					   placeholder="Основной жанр"
					   type="text">
			</div>
			@if (User.Identity.IsAuthenticated)
			{
				<div class="form-group">
					<input class="form"
						   asp-for="Book.Language"
						   placeholder="Язык оригинала"
						   type="text">
				</div>

				<div class="form-group">
					<input class="form"
						   asp-for="Book.Year"
						   placeholder="Год выпуска"
						   type="text">
				</div>

				<div class="form-group">
					<label>Параметры года выпуска:</label>

					<label class="toggle">
						<input type="radio" asp-for="YearFlag" value="More" />
						<span class="checkmark"></span>
					</label>
					<label>Больше</label>

					<label class="toggle">
						<input type="radio" asp-for="YearFlag" value="Less" />
						<span class="checkmark"></span>
					</label>
					<label>Меньше</label>

					<label class="toggle">
						<input type="radio" asp-for="YearFlag" value="Equal" />
						<span class="checkmark"></span>
					</label>
					<label>Равно</label>
				</div>
			}

			<div class="form-group">
				<input class="form"
					   asp-for="Book.Rating"
					   placeholder="Рейтинг"
					   type="text">
			</div>

			<div class="form-group">
				<label>Параметры рейтинга:</label>

				<label class="toggle">
					<input type="radio" asp-for="RatingFlag" value="More" />
					<span class="checkmark"></span>
				</label>
				<label>Больше</label>

				<label class="toggle">
					<input type="radio" asp-for="RatingFlag" value="Less" />
					<span class="checkmark"></span>
				</label>
				<label>Меньше</label>

				<label class="toggle">
					<input type="radio" asp-for="RatingFlag" value="Equal" />
					<span class="checkmark"></span>
				</label>
				<label>Равно</label>
			</div>

			@if (User.Identity.IsAuthenticated)
			{
				<div class="form-group">
					<input class="form"
						   asp-for="AuthorName"
						   placeholder="Имя автора"
						   type="text">
				</div>

				<div class="form-group">
					<input class="form"
						   asp-for="SeriesName"
						   placeholder="Название книжной серии"
						   type="text">
				</div>
			}

			<button type="submit" class="btn button">Найти</button>
		</form>
	</div>
</div></

src/Books/Views/Search/Display.cshtml
@using Books.ViewModels
@model SearchDisplayViewModel

<h2>Результаты поиска</h2>

<div class="center-text">
<div id="error-container"> </div>
</div>

@if (Model.Author != null && Model.Author.Any())
{
	<h3>Авторы:</h3>
	<table class="table-custom">
		<thead>
			<tr>
				@if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
				{
					<th>ID</th>
				}
				<th>Имя</th>
				<th>Основной жанр</th>
				@if (User.Identity.IsAuthenticated)
				{
					<th>Год рождения</th>
					<th>Год смерти</th>
				}
				<th>Страна проживания</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var author in Model.Author)
			{
				<tr>
					@if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
					{
						<td>@author.Id</td>
					}
					<td>@author.Name</td>
					<td>@author.Genre</td>
					@if (User.Identity.IsAuthenticated)
					{
						<td>@author.YearBirth</td>
						<td>@author.YearDeath</td>
					}
					<td>@author.Country</td>
				</tr>
			}
		</tbody>
	</table>
}

@if (Model.Book != null && Model.Book.Any())
{
	<h3>Книги:</h3>
	<table class="table-custom">
		<thead>
			<tr>
				@if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
				{
					<th>ID</th>
				}
				<th>Название</th>
				<th>Основной жанр</th>
				@if (User.Identity.IsAuthenticated)
				{
					<th>Язык оригинала</th>
					<th>Год выпуска</th>
				}
				<th>Рейтинг</th>
				@if (Model.AuthorName != null)
				{
					<th>Имя автора</th>
				}

				@if (Model.SeriesName != null)
				{
					<th>Название книжной серии</th>
				}
				<th></th>
			</tr>
		</thead>
		<tbody>
			@foreach (var book in Model.Book)
			{
				<tr>
					@if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
					{
						<td>@book.Id</td>
					}
					<td>@book.Name</td>
					<td>@book.Genre</td>
					@if (User.Identity.IsAuthenticated)
					{
						<td>@book.Language</td>
						<td>@book.Year</td>
					}
					<td>@book.Rating</td>

					@if (Model.AuthorName != null)
					{
						<td>@Model.AuthorName</td>
					}

					@if (Model.SeriesName != null)
					{
						<td>@Model.SeriesName</td>
					}

					@if (User.Identity.IsAuthenticated)
					{
						<td>
							<form id="addBookForm-@book.Id" asp-action="AddBook" asp-controller="Bookshelf" method="post" class="text-center">
								<input type="hidden" name="idBook" value="@book.Id" />
								<button type="button" id="addButton-@book.Id" class="btn button mx-auto" onclick="addBookAndDisableButton(@book.Id)">Добавить на книжную полку</button>
							</form>
						</td>
					}
				</tr>
			}
		</tbody>
	</table>
}

@if (Model.Series != null && Model.Series.Any())
{
	<h3>Книжные серии:</h3>
	<table class="table-custom">
		<thead>
			<tr>
				@if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
				{
					<th>ID</th>
				}
				<th>Название</th>
				<th>Основной жанр</th>
				@if (User.Identity.IsAuthenticated)
				{
					<th>Издательство</th>
					<th>Год первого выпуска</th>
				}
				<th>Рейтинг</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var series in Model.Series)
			{
				<tr>
					@if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
					{
						<td>@series.Id</td>
					}
					<td>@series.Name</td>
					<td>@series.Genre</td>
					@if (User.Identity.IsAuthenticated)
					{
						<td>@series.Publisher</td>
						<td>@series.Year</td>
					}
					<td>@series.Rating</td>
				</tr>
			}
		</tbody>
	</table>
}

@if ((Model.Book == null || !Model.Book.Any()) &&
		(Model.Author == null || !Model.Author.Any()) &&
		(Model.Series == null || !Model.Series.Any()))
{
	<p>Ничего не найдено...</p>
}

<script>
	function addBookAndDisableButton(bookId) {
		disableButton(bookId); // Вызываем функцию disableButton сначала
		addBook(bookId); // Затем вызываем функцию addBook
	}

	function addBook(bookId) {
		const formData = {
			idBook: bookId,
		};

		$.ajax({
			type: "POST",
			url: "/Bookshelf/AddBook",
			data: formData,
			success: function (response) {
				// Обработка успешного ответа, если нужно
				if (response.success) {
					console.log(response.message); // Выводим сообщение об успешном добавлении
					// Можете выполнить другие действия, например, обновить информацию на странице
				} else {
					showError(response.message); // Вызываем функцию showError с сообщением об ошибке
				}
			},
			error: function (error) {
				// Обработка ошибки, если нужно
				console.error(error);
				showError("Произошла ошибка при выполнении запроса."); // Здесь можно отобразить общее сообщение об ошибке AJAX запроса
			}
		});
	}

	function disableButton(bookId) {
		const addButton = document.getElementById(`addButton-${bookId}`);
		addButton.classList.add("disabled");
	}

	function showError(errorMessage) {
		const errorContainer = document.getElementById('error-container');
		errorContainer.innerHTML = '<div class="alert alert-danger">' + errorMessage + '</div>';
	}
</script>

src/Books/Views/Search/SeriesSearch.cshtml
@using Books.ViewModels
@model SeriesSearchViewModel

<div class="advancedSearch-container">
	<div class="advancedSearch-inner-container">
		<h2>Расширенный поиск книжных серий</h2>

		@if (TempData["ErrorMessage"] != null)
		{
			<div class="alert alert-danger text-center">@TempData["ErrorMessage"]</div>
		}

		<form asp-action="SeriesSearch" asp-controller="Search">
			<div class="form-group">
				<input class="form"
					   asp-for="Series.Name"
					   placeholder="Название"
					   type="text">
			</div>
			<div class="form-group">
				<input class="form"
					   asp-for="Series.Genre"
					   placeholder="Основной жанр"
					   type="text">
			</div>
			@if (User.Identity.IsAuthenticated)
			{
				<div class="form-group">
					<input class="form"
						   asp-for="Series.Publisher"
						   placeholder="Издатель"
						   type="text">
				</div>

				<div class="form-group">
					<input class="form"
						   asp-for="Series.Year"
						   placeholder="Год первого выпуска"
						   type="text">
				</div>

				<div class="form-group">
					<label>Параметры года первого выпуска:</label>

					<label class="toggle">
						<input type="radio" asp-for="YearFlag" value="More" />
						<span class="checkmark"></span>
					</label>
					<label>Больше</label>

					<label class="toggle">
						<input type="radio" asp-for="YearFlag" value="Less" />
						<span class="checkmark"></span>
					</label>
					<label>Меньше</label>

					<label class="toggle">
						<input type="radio" asp-for="YearFlag" value="Equal" />
						<span class="checkmark"></span>
					</label>
					<label>Равно</label>
				</div>
			}

			<div class="form-group">
				<input class="form"
					   asp-for="Series.Rating"
					   placeholder="Рейтинг"
					   type="text">
			</div>

			<div class="form-group">
				<label>Параметры рейтинга:</label>

				<label class="toggle">
					<input type="radio" asp-for="RatingFlag" value="More" />
					<span class="checkmark"></span>
				</label>
				<label>Больше</label>

				<label class="toggle">
					<input type="radio" asp-for="RatingFlag" value="Less" />
					<span class="checkmark"></span>
				</label>
				<label>Меньше</label>

				<label class="toggle">
					<input type="radio" asp-for="RatingFlag" value="Equal" />
					<span class="checkmark"></span>
				</label>
				<label>Равно</label>
			</div>

			<button type="submit" class="btn button">Найти</button>
		</form>
	</div>
</div></

src/Books/Views/Search/SimpleSearch.cshtml
@model string

<div class="center-container">

	<h2>Поиск</h2>

	@if (TempData["ErrorMessage"] != null)
	{
		<div class="alert alert-danger text-center">@TempData["ErrorMessage"]</div>
	}

	<form asp-action="SimpleSearch" asp-controller="Search">
		<div class="form-group">
			<input class="form"
				   name="name"
				   value="@Model"
				   placeholder="Введите название произведения, книжной серии или имя автора..."
				   type="text">
		</div>
		<button type="submit" class="btn button">Найти</button>

	</form>
</div>